// <auto-generated />
using System;
using FaithLife.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FaithLife.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220817103943_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FaithLife.Api.Model.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Minister")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Services")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventDescription = "God will send his Holy spirit to you",
                            EventName = "The Holy spirit",
                            Minister = "Pastor Abraham",
                            Services = 0
                        },
                        new
                        {
                            EventId = 2,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventDescription = "God will send his Holy spirit to you",
                            EventName = "The Holy spirit",
                            Minister = "Pastor Abraham",
                            Services = 0
                        },
                        new
                        {
                            EventId = 3,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventDescription = "God will send his Holy spirit to you",
                            EventName = "The Holy spirit",
                            Minister = "Pastor Abraham",
                            Services = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
